project:
  type: website
  output-dir: docs

website:
  title: "Redesign"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - redesign.qmd  
      - about.qmd
      - Code.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

